server:
  port: 50101

spring:
  main:
    log-startup-info: false

  output:
    ansi:
      enabled: always

  application:
    name: backend-api

  datasource:
    driver: com.mysql.cj.jdbc.Driver
    url: ENC(qjNaPPLzFge1WrY/3fCZh0i9xle9TyTQDgtOQ1QvKK5WNbhDMTq1+GwQve/uJZMXujdnNgTameAOZNSxOGK5HNNr3c5nuzO6TDjkfj+z9+5QwgRqvN+Mm5aLWqkXmyJ87aIXvMUhcpHEBZUt+6PKvVySixj0Jptg3TqMS1LWRxXiwpB9g9zuNsB1Af7+dIRB)
    username: ENC(vxW8jpyMObRjCT6No7wXiSWEpqE0/G6oUkUG+Ibwi0SpDtEjuFnSVSSJ30m4iWHO)
    password: ENC(pB7Q0QMvyOlVOLjuaW27snQ6twwJHcgd4cBOhfeR2VxDuo+r4XuytdsZfcIDwuaW)


    hikari:
      maximum-pool-size: 20 # 커넥션 풀의 최대 크기 설정
      minimum-idle: 5 # 유휴 커넥션을 유지할 최소한의 커넥션 수 설정
      idle-timeout: 30000 # 유휴 컨넥션의 최대 유지 시간 설정 (30초)
      max-lifetime: 60000 # 커넥션의 최대 생명 주기 설정 (60초)
      connection-timeout: 3000 # 커넥션 타임아웃 설정 (3초)
      pool-name: HikariCP
      validation-timeout: 5000 # 커넥션 유효성 검사 타임아웃 설정 (5초)
      leak-detection-threshold: 10000 # 커넥션 누수 감지 타임아웃 설정 (10초)
      auto-commit: true

      # 로그 관련 설정
      data-source-properties:
        dataSource.logWriter: # 로그 작성 구현체 지정
        dataSource.logUnclosedConnections: true  # 사용하지 않은 커넥션의 로깅 여부 지정

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 20MB

  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher

  data:
    redis:
      sentinel:
        master: mymaster
        nodes:
          - localhost:26379
          - localhost:26380
          - localhost:26381
      timeout: 1000 # milliseconds (Redis 연결 타임아웃)
      lettuce:
        pool:
          max-active: 16    # 최대 커넥션 개수
          max-idle: 8       # 최대 idle 커넥션 수
          min-idle: 2       # 최소 idle 커넥션 수
          max-wait: 5000    # 커넥션 부족 시 최대 대기 시간 (ms)
        shutdown-timeout: 100 # Lettuce 클라이언트 종료시 최대 대기 시간 (ms)
        cluster:
          refresh:
            adaptive: true  # 동적으로 클러스터 상태 감지 (Sentinel에서도 사용 가능)
            period: 30000   # 정기적으로 클러스터 토폴로지 리프레시 주기 (ms)
    cache:
      type: redis

logging:
  level:
    com.zaxxer.hikari: DEBUG

token:
  access_expiration_time: 3600000 # (1000 * 60) * 60 = 1시간
  refresh_expiration_time: 15778800000 # (1000 * 60) * 60 * 24 * 30 * 6 = 6개월
  secret: myJwtSecretKey

authorization:
  token:
    header:
      access-name: AccessToken
      refresh-name: RefreshToken
      prefix: Bearer

jasypt:
  encryptor:
    password: ${JASYPT_ENCRYPTOR_PASSWORD:test-secret-key}
    algorithm: PBEWITHSHA256AND256BITAES-CBC-BC
    iv-generator-classname: org.jasypt.iv.RandomIvGenerator
    pool-size: 1
    string-output-type: base64
